"use client";
import ManualCalculatorLayout from "@/components/tools/ManualCalculatorLayout";
import {useMemo,useState} from "react";
import type { ReactNode } from "react";
const num=(v:number)=>Number.isFinite(v)?v:0; const fmt=(v:number,d=2)=>num(v).toLocaleString("ko-KR",{maximumFractionDigits:d}); const won=(v:number)=>Math.round(num(v)).toLocaleString("ko-KR")+"원";
function F({label,value,onChange,step="1"}:{label:string;value:number;onChange:(v:number)=>void;step?:string}){return <div className="field"><label>{label}</label><input type="number" value={value} step={step} onChange={e=>onChange(Number(e.target.value))}/></div>}
function R({main,items,note}:{main:string;items:[string,string][];note?:string}){return <section className="panel"><div className="result-main">{main}</div><div className="stats">{items.map(([a,b])=><div className="stat" key={a}><small>{a}</small><strong>{b}</strong></div>)}</div>{note?<div className="notice" style={{marginTop:16}}>{note}</div>:null}<div className="action-row no-print"><button className="secondary" type="button" onClick={()=>window.print()}>인쇄 · PDF 저장</button></div></section>}
function L({children,result}:{children:ReactNode;result:ReactNode}){return <ManualCalculatorLayout inputs={children} result={result}/>;}
export function CagrCalculator(){const[a,setA]=useState(10000000),[b,setB]=useState(15000000),[y,setY]=useState(5);const r=useMemo(()=>a>0&&b>=0&&y>0?(Math.pow(b/a,1/y)-1)*100:0,[a,b,y]);return <L result={<R main={`CAGR ${fmt(r)}%`} items={[["시작값",won(a)],["최종값",won(b)],["기간",`${fmt(y)}년`],["연평균 성장률",`${fmt(r)}%`]]}/>}><F label="시작 금액" value={a} onChange={setA}/><F label="최종 금액" value={b} onChange={setB}/><F label="기간(년)" value={y} onChange={setY} step="0.1"/></L>}
export function RealReturnCalculator(){const[n,setN]=useState(6),[i,setI]=useState(3);const r=((1+n/100)/(1+i/100)-1)*100;return <L result={<R main={`실질수익률 ${fmt(r)}%`} items={[["명목수익률",`${fmt(n)}%`],["물가상승률",`${fmt(i)}%`],["실질수익률",`${fmt(r)}%`],["구매력 배수",fmt((1+n/100)/(1+i/100),4)]]}/>}><F label="명목수익률(%)" value={n} onChange={setN} step="0.1"/><F label="물가상승률(%)" value={i} onChange={setI} step="0.1"/></L>}
export function CurtainSizeCalculator(){const[w,setW]=useState(240),[fold,setFold]=useState(1.8),[panel,setPanel]=useState(140);const need=Math.max(0,w)*Math.max(1,fold),count=Math.ceil(need/Math.max(1,panel));return <L result={<R main={`${count}장 필요`} items={[["창문 폭",`${fmt(w)}cm`],["필요 총폭",`${fmt(need)}cm`],["1장 폭",`${fmt(panel)}cm`],["예상 장수",`${count}장`]]}/>}><F label="창문 폭(cm)" value={w} onChange={setW}/><F label="주름 배수" value={fold} onChange={setFold} step="0.1"/><F label="커튼 1장 폭(cm)" value={panel} onChange={setPanel}/></L>}
export function StorageVolumeCalculator(){const[w,setW]=useState(60),[d,setD]=useState(40),[h,setH]=useState(35);const cc=Math.max(0,w*d*h),l=cc/1000,m3=cc/1000000;return <L result={<R main={`${fmt(l,1)}L`} items={[["부피",`${fmt(cc,0)}cm³`],["리터",`${fmt(l,1)}L`],["세제곱미터",`${fmt(m3,3)}㎥`],["치수",`${w}×${d}×${h}cm`]]}/>}><F label="가로(cm)" value={w} onChange={setW}/><F label="세로(cm)" value={d} onChange={setD}/><F label="높이(cm)" value={h} onChange={setH}/></L>}
const tire=(width:number,aspect:number,inch:number)=>inch*25.4+2*(width*aspect/100);
export function TireDiameterCalculator(){const[w1,setW1]=useState(205),[a1,setA1]=useState(55),[r1,setR1]=useState(16),[w2,setW2]=useState(215),[a2,setA2]=useState(50),[r2,setR2]=useState(17);const d1=tire(w1,a1,r1),d2=tire(w2,a2,r2),diff=d1?((d2-d1)/d1*100):0;return <L result={<R main={`외경 차이 ${fmt(diff)}%`} items={[["기존 외경",`${fmt(d1,1)}mm`],["변경 외경",`${fmt(d2,1)}mm`],["둘레 차이",`${fmt(Math.PI*(d2-d1),1)}mm`],["차이율",`${fmt(diff)}%`]]} note="장착 가능 여부는 차량 제조사 권장 규격을 우선 확인하세요."/>}><F label="기존 폭(mm)" value={w1} onChange={setW1}/><F label="기존 편평비(%)" value={a1} onChange={setA1}/><F label="기존 휠(inch)" value={r1} onChange={setR1}/><F label="변경 폭(mm)" value={w2} onChange={setW2}/><F label="변경 편평비(%)" value={a2} onChange={setA2}/><F label="변경 휠(inch)" value={r2} onChange={setR2}/></L>}
export function EvChargeTimeCalculator(){const[cap,setCap]=useState(77),[start,setStart]=useState(20),[target,setTarget]=useState(80),[kw,setKw]=useState(7);const energy=Math.max(0,cap)*Math.max(0,target-start)/100,hours=energy/Math.max(.1,kw);return <L result={<R main={`약 ${fmt(hours,1)}시간`} items={[["필요 전력량",`${fmt(energy,1)}kWh`],["충전 출력",`${fmt(kw,1)}kW`],["이론 충전시간",`${fmt(hours,1)}시간`],["SOC 변화",`${fmt(start,0)}% → ${fmt(target,0)}%`]]}/>}><F label="배터리 용량(kWh)" value={cap} onChange={setCap} step="0.1"/><F label="시작 충전율(%)" value={start} onChange={setStart}/><F label="목표 충전율(%)" value={target} onChange={setTarget}/><F label="충전 출력(kW)" value={kw} onChange={setKw} step="0.1"/></L>}
export function CashbackPriceCalculator(){const[p,setP]=useState(200000),[rate,setRate]=useState(7),[cap,setCap]=useState(10000);const raw=Math.max(0,p)*Math.max(0,rate)/100,cb=cap>0?Math.min(raw,cap):raw,net=Math.max(0,p-cb);return <L result={<R main={`실질구매가 ${won(net)}`} items={[["결제금액",won(p)],["예상 캐시백",won(cb)],["실질구매가",won(net)],["실질 혜택률",`${fmt(p?cb/p*100:0)}%`]]}/>}><F label="결제금액" value={p} onChange={setP}/><F label="캐시백·적립률(%)" value={rate} onChange={setRate} step="0.1"/><F label="최대 혜택 한도(0=없음)" value={cap} onChange={setCap}/></L>}
export function PricePerUseCalculator(){const[p,setP]=useState(150000),[uses,setUses]=useState(300),[maint,setMaint]=useState(0);const total=Math.max(0,p)+Math.max(0,maint),per=total/Math.max(1,uses);return <L result={<R main={`1회당 ${won(per)}`} items={[["구매가격",won(p)],["추가 유지비",won(maint)],["예상 사용횟수",`${fmt(uses,0)}회`],["1회당 비용",won(per)]]}/>}><F label="구매가격" value={p} onChange={setP}/><F label="예상 총 사용횟수" value={uses} onChange={setUses}/><F label="예상 추가 유지비" value={maint} onChange={setMaint}/></L>}
export function BreakDeductionCalculator(){const[start,setStart]=useState(9),[end,setEnd]=useState(18.5),[breakMin,setBreak]=useState(60);const span=((end-start)+24)%24||24,work=Math.max(0,span-breakMin/60);return <L result={<R main={`실근무 ${fmt(work,2)}시간`} items={[["체류시간",`${fmt(span,2)}시간`],["휴게시간",`${fmt(breakMin,0)}분`],["실근무시간",`${fmt(work,2)}시간`],["분 환산",`${fmt(work*60,0)}분`]]} note="시각은 24시간 소수 형식(예: 18:30 → 18.5)으로 입력하세요."/>}><F label="출근 시각" value={start} onChange={setStart} step="0.25"/><F label="퇴근 시각" value={end} onChange={setEnd} step="0.25"/><F label="총 휴게시간(분)" value={breakMin} onChange={setBreak}/></L>}
export function BillableUtilizationCalculator(){const[total,setTotal]=useState(160),[bill,setBill]=useState(112);const rate=Math.max(0,bill)/Math.max(1,total)*100;return <L result={<R main={`청구가능 비율 ${fmt(rate)}%`} items={[["총 업무시간",`${fmt(total)}시간`],["청구가능시간",`${fmt(bill)}시간`],["비청구시간",`${fmt(Math.max(0,total-bill))}시간`],["가동률",`${fmt(rate)}%`]]}/>}><F label="총 업무시간" value={total} onChange={setTotal} step="0.5"/><F label="청구가능시간" value={bill} onChange={setBill} step="0.5"/></L>}
export function RatioSplitCalculator(){const[total,setTotal]=useState(300000),[a,setA]=useState(2),[b,setB]=useState(3);const s=Math.max(0,a)+Math.max(0,b),av=s?total*a/s:0,bv=s?total*b/s:0;return <L result={<R main={`${fmt(a,1)} : ${fmt(b,1)} 분배`} items={[["전체값",fmt(total)],["첫 번째 몫",fmt(av)],["두 번째 몫",fmt(bv)],["합계",fmt(av+bv)]]}/>}><F label="전체 값" value={total} onChange={setTotal}/><F label="첫 번째 비율" value={a} onChange={setA} step="0.1"/><F label="두 번째 비율" value={b} onChange={setB} step="0.1"/></L>}
export function WeightedAverageCalculator(){const[v1,setV1]=useState(80),[w1,setW1]=useState(30),[v2,setV2]=useState(95),[w2,setW2]=useState(70);const s=w1+w2,avg=s?(v1*w1+v2*w2)/s:0;return <L result={<R main={`가중평균 ${fmt(avg,2)}`} items={[["값 1",fmt(v1)],["값 2",fmt(v2)],["가중치 합",fmt(s)],["가중평균",fmt(avg,2)]]}/>}><F label="값 1" value={v1} onChange={setV1} step="0.1"/><F label="가중치 1" value={w1} onChange={setW1} step="0.1"/><F label="값 2" value={v2} onChange={setV2} step="0.1"/><F label="가중치 2" value={w2} onChange={setW2} step="0.1"/></L>}
