"use client";
import { useMemo, useState } from "react";
import type { ReactNode } from "react";

const num=(v:number)=>Number.isFinite(v)?v:0;
const won=(v:number)=>Math.round(num(v)).toLocaleString("ko-KR")+"원";
const nfmt=(v:number,d=1)=>num(v).toLocaleString("ko-KR",{maximumFractionDigits:d});

function Field({label,value,onChange,step="1",min="0"}:{label:string;value:number;onChange:(v:number)=>void;step?:string;min?:string}){return <div className="field"><label>{label}</label><input type="number" min={min} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></div>}
function Result({main,items,note}:{main:string;items:[string,string][];note?:string}){return <section className="panel"><div className="result-main">{main}</div><div className="stats">{items.map(([k,v])=><div className="stat" key={k}><small>{k}</small><strong>{v}</strong></div>)}</div>{note?<div className="notice" style={{marginTop:16}}>{note}</div>:null}<div className="action-row no-print"><button className="secondary" type="button" onClick={()=>window.print()}>인쇄 · PDF 저장</button></div></section>}
function Layout({inputs,result}:{inputs:ReactNode;result:ReactNode}){return <div className="tool-layout"><section className="panel">{inputs}</section>{result}</div>}

export function SavingsGoalCalculator(){const [goal,setGoal]=useState(30000000),[current,setCurrent]=useState(5000000),[months,setMonths]=useState(24),[rate,setRate]=useState(3);const r=useMemo(()=>{const gap=Math.max(0,goal-current),m=Math.max(1,months),monthlyRate=Math.max(0,rate)/100/12;const monthly=monthlyRate>0?gap*monthlyRate/(Math.pow(1+monthlyRate,m)-1):gap/m;const total=monthly*m;return{gap,monthly,total,interest:Math.max(0,total-gap)}},[goal,current,months,rate]);return <Layout inputs={<><Field label="목표 금액" value={goal} onChange={setGoal}/><Field label="현재 모은 금액" value={current} onChange={setCurrent}/><Field label="목표 기간(개월)" value={months} onChange={setMonths}/><Field label="예상 연 수익률(%)" value={rate} onChange={setRate} step="0.1"/></>} result={<Result main={`월 ${won(r.monthly)} 필요`} items={[["남은 목표",won(r.gap)],["예상 납입 합계",won(r.total)],["예상 수익 기여",won(r.interest)],["기간",`${months}개월`]]}/>}/>}

export function EmergencyFundCalculator(){const [fixed,setFixed]=useState(1800000),[variable,setVariable]=useState(700000),[months,setMonths]=useState(6),[saved,setSaved]=useState(5000000);const r=useMemo(()=>{const monthly=Math.max(0,fixed)+Math.max(0,variable),target=monthly*Math.max(1,months),gap=Math.max(0,target-saved);return{monthly,target,gap,ratio:target?Math.min(100,Math.max(0,saved)/target*100):100}},[fixed,variable,months,saved]);return <Layout inputs={<><Field label="월 고정지출" value={fixed} onChange={setFixed}/><Field label="월 필수 변동지출" value={variable} onChange={setVariable}/><Field label="비상자금 목표 개월" value={months} onChange={setMonths}/><Field label="현재 비상자금" value={saved} onChange={setSaved}/></>} result={<Result main={`목표 비상자금 ${won(r.target)}`} items={[["월 필수생활비",won(r.monthly)],["추가 필요금액",won(r.gap)],["현재 달성률",`${nfmt(r.ratio)}%`],["목표 기간",`${months}개월치`]]}/>}/>}

export function RentShareCalculator(){const [rent,setRent]=useState(1200000),[utility,setUtility]=useState(250000),[people,setPeople]=useState(3),[extra,setExtra]=useState(0);const r=useMemo(()=>{const total=Math.max(0,rent)+Math.max(0,utility)+Math.max(0,extra),p=Math.max(1,people);return{total,per:total/p}},[rent,utility,people,extra]);return <Layout inputs={<><Field label="월세·관리비" value={rent} onChange={setRent}/><Field label="공과금" value={utility} onChange={setUtility}/><Field label="기타 공동비용" value={extra} onChange={setExtra}/><Field label="분담 인원" value={people} onChange={setPeople}/></>} result={<Result main={`1인 분담액 ${won(r.per)}`} items={[["총 공동비용",won(r.total)],["분담 인원",`${Math.max(1,people)}명`],["1인 분담액",won(r.per)],["연간 1인 부담",won(r.per*12)]]}/>}/>}

export function RenovationBudgetCalculator(){const [area,setArea]=useState(25),[unit,setUnit]=useState(800000),[furniture,setFurniture]=useState(5000000),[reserve,setReserve]=useState(10);const r=useMemo(()=>{const base=Math.max(0,area)*Math.max(0,unit),subtotal=base+Math.max(0,furniture),cont=subtotal*Math.max(0,reserve)/100;return{base,subtotal,cont,total:subtotal+cont}},[area,unit,furniture,reserve]);return <Layout inputs={<><Field label="공사 면적(평)" value={area} onChange={setArea} step="0.1"/><Field label="평당 예상 공사비" value={unit} onChange={setUnit}/><Field label="가구·가전 예산" value={furniture} onChange={setFurniture}/><Field label="예비비(%)" value={reserve} onChange={setReserve} step="1"/></>} result={<Result main={`총 예산 ${won(r.total)}`} items={[["기본 공사비",won(r.base)],["가구 포함 소계",won(r.subtotal)],["예비비",won(r.cont)],["총 예상예산",won(r.total)]]}/>}/>}

export function TripTotalCostCalculator(){const [distance,setDistance]=useState(420),[eff,setEff]=useState(12),[fuel,setFuel]=useState(1680),[toll,setToll]=useState(28000),[parking,setParking]=useState(15000);const r=useMemo(()=>{const liters=Math.max(0,distance)/Math.max(.1,eff),fuelCost=liters*Math.max(0,fuel),total=fuelCost+Math.max(0,toll)+Math.max(0,parking);return{liters,fuelCost,total,perKm:distance>0?total/distance:0}},[distance,eff,fuel,toll,parking]);return <Layout inputs={<><Field label="총 주행거리(km)" value={distance} onChange={setDistance}/><Field label="평균 연비(km/L)" value={eff} onChange={setEff} step="0.1"/><Field label="유가(원/L)" value={fuel} onChange={setFuel}/><Field label="통행료" value={toll} onChange={setToll}/><Field label="주차비" value={parking} onChange={setParking}/></>} result={<Result main={`여행 이동비 ${won(r.total)}`} items={[["예상 연료",`${nfmt(r.liters)}L`],["연료비",won(r.fuelCost)],["총 이동비",won(r.total)],["km당 비용",won(r.perKm)]]}/>}/>}

export function AnnualMileageCalculator(){const [daily,setDaily]=useState(32),[workdays,setWorkdays]=useState(230),[extra,setExtra]=useState(4000);const r=useMemo(()=>{const commute=Math.max(0,daily)*Math.max(0,workdays),total=commute+Math.max(0,extra);return{commute,total,monthly:total/12,weekly:total/52}},[daily,workdays,extra]);return <Layout inputs={<><Field label="출퇴근 왕복거리(km)" value={daily} onChange={setDaily}/><Field label="연간 출근일수" value={workdays} onChange={setWorkdays}/><Field label="기타 연간 주행거리(km)" value={extra} onChange={setExtra}/></>} result={<Result main={`연간 예상 주행 ${nfmt(r.total,0)}km`} items={[["출퇴근 주행",`${nfmt(r.commute,0)}km`],["월평균",`${nfmt(r.monthly,0)}km`],["주평균",`${nfmt(r.weekly,0)}km`],["연간 합계",`${nfmt(r.total,0)}km`]]}/>}/>}

export function UnitPriceCalculator(){const [priceA,setPriceA]=useState(12900),[qtyA,setQtyA]=useState(800),[priceB,setPriceB]=useState(16900),[qtyB,setQtyB]=useState(1200);const r=useMemo(()=>{const a=Math.max(0,priceA)/Math.max(.0001,qtyA),b=Math.max(0,priceB)/Math.max(.0001,qtyB),winner=a<=b?"A 상품":"B 상품",diff=Math.abs(a-b);return{a,b,winner,diff}},[priceA,qtyA,priceB,qtyB]);return <Layout inputs={<><Field label="A 상품 가격" value={priceA} onChange={setPriceA}/><Field label="A 용량·수량" value={qtyA} onChange={setQtyA} step="0.1"/><Field label="B 상품 가격" value={priceB} onChange={setPriceB}/><Field label="B 용량·수량" value={qtyB} onChange={setQtyB} step="0.1"/></>} result={<Result main={`${r.winner}이 단위당 저렴`} items={[["A 단가",won(r.a)],["B 단가",won(r.b)],["단위당 차이",won(r.diff)],["추천",r.winner]]} note="두 상품의 용량·수량 단위를 동일하게 맞춰 입력하세요."/>}/>}

export function InstallmentTotalCalculator(){const [price,setPrice]=useState(1200000),[months,setMonths]=useState(12),[fee,setFee]=useState(5.9),[down,setDown]=useState(0);const r=useMemo(()=>{const principal=Math.max(0,price-down),m=Math.max(1,months),monthlyRate=Math.max(0,fee)/100/12,monthly=monthlyRate>0?principal*monthlyRate*Math.pow(1+monthlyRate,m)/(Math.pow(1+monthlyRate,m)-1):principal/m,total=monthly*m+Math.max(0,down);return{principal,monthly,total,cost:total-price}},[price,months,fee,down]);return <Layout inputs={<><Field label="구매가격" value={price} onChange={setPrice}/><Field label="선결제금" value={down} onChange={setDown}/><Field label="할부 개월" value={months} onChange={setMonths}/><Field label="연 할부수수료율(%)" value={fee} onChange={setFee} step="0.1"/></>} result={<Result main={`월 예상납부 ${won(r.monthly)}`} items={[["할부 원금",won(r.principal)],["월 납부액",won(r.monthly)],["총 지출",won(r.total)],["추가 금융비용",won(r.cost)]]} note="카드사 실제 수수료 계산 방식과 무이자 행사 조건에 따라 청구액이 달라질 수 있습니다."/>}/>}

export function WeeklyPayCalculator(){const [hourly,setHourly]=useState(12000),[hours,setHours]=useState(32),[days,setDays]=useState(4),[extra,setExtra]=useState(0);const r=useMemo(()=>{const base=Math.max(0,hourly)*Math.max(0,hours),total=base+Math.max(0,extra);return{base,total,daily:days>0?total/days:0,monthly:total*52/12}},[hourly,hours,days,extra]);return <Layout inputs={<><Field label="시급" value={hourly} onChange={setHourly}/><Field label="주 근무시간" value={hours} onChange={setHours} step="0.5"/><Field label="주 근무일수" value={days} onChange={setDays}/><Field label="추가 수당(주)" value={extra} onChange={setExtra}/></>} result={<Result main={`예상 주급 ${won(r.total)}`} items={[["기본 주급",won(r.base)],["추가 수당",won(extra)],["1일 평균",won(r.daily)],["월 환산 참고",won(r.monthly)]]} note="주휴수당·연장·야간·휴일수당 등 법정수당은 근로조건에 따라 별도 계산이 필요합니다."/>}/>}

export function FreelanceRateCalculator(){const [target,setTarget]=useState(4000000),[expenses,setExpenses]=useState(600000),[hours,setHours]=useState(120),[buffer,setBuffer]=useState(20);const r=useMemo(()=>{const needed=Math.max(0,target)+Math.max(0,expenses),billable=Math.max(1,hours),base=needed/billable,rate=base*(1+Math.max(0,buffer)/100);return{needed,base,rate,day:rate*8}},[target,expenses,hours,buffer]);return <Layout inputs={<><Field label="월 목표 수입" value={target} onChange={setTarget}/><Field label="월 업무비용" value={expenses} onChange={setExpenses}/><Field label="월 청구 가능시간" value={hours} onChange={setHours}/><Field label="비가동·위험 여유율(%)" value={buffer} onChange={setBuffer}/></>} result={<Result main={`권장 시간단가 ${won(r.rate)}`} items={[["필요 월매출",won(r.needed)],["손익분기 시간단가",won(r.base)],["권장 시간단가",won(r.rate)],["8시간 일단가",won(r.day)]]}/>}/>}

export function DdayCalculator(){const today=new Date();const defaultDate=new Date(today.getFullYear(),today.getMonth()+1,today.getDate()).toISOString().slice(0,10);const [target,setTarget]=useState(defaultDate);const d=useMemo(()=>{const start=new Date();start.setHours(0,0,0,0);const t=new Date(target+"T00:00:00");const days=Math.round((t.getTime()-start.getTime())/86400000);return{days,weeks:days/7}},[target]);return <div className="tool-layout"><section className="panel"><div className="field"><label>목표 날짜</label><input type="date" value={target} onChange={e=>setTarget(e.target.value)}/></div></section><Result main={d.days===0?"오늘이 D-Day":d.days>0?`D-${d.days}`:`D+${Math.abs(d.days)}`} items={[["남은/지난 일수",`${Math.abs(d.days)}일`],["주 단위",`${nfmt(Math.abs(d.weeks))}주`],["목표 날짜",target],["상태",d.days>0?"앞으로":"지남"]]}/></div>}

export function EventBudgetCalculator(){const [people,setPeople]=useState(20),[food,setFood]=useState(25000),[place,setPlace]=useState(300000),[etc,setEtc]=useState(150000),[reserve,setReserve]=useState(10);const r=useMemo(()=>{const meal=Math.max(0,people)*Math.max(0,food),subtotal=meal+Math.max(0,place)+Math.max(0,etc),buffer=subtotal*Math.max(0,reserve)/100,total=subtotal+buffer;return{meal,subtotal,buffer,total,per:people>0?total/people:0}},[people,food,place,etc,reserve]);return <Layout inputs={<><Field label="참석 인원" value={people} onChange={setPeople}/><Field label="1인 식음료비" value={food} onChange={setFood}/><Field label="장소비" value={place} onChange={setPlace}/><Field label="기타 비용" value={etc} onChange={setEtc}/><Field label="예비비(%)" value={reserve} onChange={setReserve}/></>} result={<Result main={`행사 총예산 ${won(r.total)}`} items={[["식음료",won(r.meal)],["예비비",won(r.buffer)],["1인당 총비용",won(r.per)],["총예산",won(r.total)]]}/>}/>}
