"use client";
import { useState } from "react";
const fmt=(n:number,d=2)=>Number.isFinite(n)?n.toLocaleString("ko-KR",{maximumFractionDigits:d}):"0";
const won=(n:number)=>`${Math.round(n).toLocaleString("ko-KR")}원`;
const Layout=({children,result}:{children:React.ReactNode,result:React.ReactNode})=><div className="tool-layout"><section className="panel">{children}</section><section className="panel">{result}<div className="action-row no-print"><button className="secondary" type="button" onClick={()=>window.print()}>인쇄 · PDF 저장</button></div></section></div>;
const Num=({label,value,set,step=1}:{label:string,value:number,set:(n:number)=>void,step?:number})=><div className="field"><label>{label}</label><input type="number" min="0" step={step} value={value} onChange={e=>set(Number(e.target.value))}/></div>;
export function AreaPyeongCalculator(){const [sqm,setSqm]=useState(84);const [p,setP]=useState(84/3.305785);return <Layout result={<><span className="category-label">변환 결과</span><div className="result-main">{fmt(sqm/3.305785)}평</div><div className="stats"><div className="stat"><small>입력 ㎡</small><strong>{fmt(sqm)}㎡</strong></div><div className="stat"><small>평 입력 환산</small><strong>{fmt(p*3.305785)}㎡</strong></div></div></>}>{<><Num label="제곱미터(㎡)" value={sqm} set={setSqm} step={0.01}/><Num label="평" value={p} set={setP} step={0.01}/></>}</Layout>}
export function RoomAreaCalculator(){const [w,setW]=useState(3.6),[l,setL]=useState(4.2);const a=w*l;return <Layout result={<><span className="category-label">방 면적</span><div className="result-main">{fmt(a)}㎡ · {fmt(a/3.305785)}평</div></>}><Num label="가로(m)" value={w} set={setW} step={0.01}/><Num label="세로(m)" value={l} set={setL} step={0.01}/></Layout>}
export function PaintQuantityCalculator(){const [a,setA]=useState(35),[c,setC]=useState(2),[cover,setCover]=useState(10),[waste,setWaste]=useState(10);const liters=a*c/Math.max(cover,0.01)*(1+waste/100);return <Layout result={<><span className="category-label">필요 페인트</span><div className="result-main">약 {fmt(liters,1)}L</div></>}><Num label="도장 면적(㎡)" value={a} set={setA} step={0.1}/><Num label="도장 횟수" value={c} set={setC}/><Num label="1L당 도포면적(㎡)" value={cover} set={setCover} step={0.1}/><Num label="여유율(%)" value={waste} set={setWaste}/></Layout>}
export function WallpaperQuantityCalculator(){const [a,setA]=useState(45),[roll,setRoll]=useState(15),[waste,setWaste]=useState(10);const n=Math.ceil(a*(1+waste/100)/Math.max(roll,0.01));return <Layout result={<><span className="category-label">필요 벽지</span><div className="result-main">약 {n}롤</div></>}><Num label="도배 면적(㎡)" value={a} set={setA} step={0.1}/><Num label="1롤 실사용 면적(㎡)" value={roll} set={setRoll} step={0.1}/><Num label="여유율(%)" value={waste} set={setWaste}/></Layout>}
export function TileQuantityCalculator(){const [a,setA]=useState(10),[w,setW]=useState(600),[h,setH]=useState(600),[waste,setWaste]=useState(10);const one=w/1000*h/1000;const n=Math.ceil(a*(1+waste/100)/Math.max(one,0.0001));return <Layout result={<><span className="category-label">필요 타일</span><div className="result-main">약 {n}장</div><div className="stats"><div className="stat"><small>1장 면적</small><strong>{fmt(one,3)}㎡</strong></div></div></>}><Num label="시공 면적(㎡)" value={a} set={setA} step={0.1}/><Num label="타일 가로(mm)" value={w} set={setW}/><Num label="타일 세로(mm)" value={h} set={setH}/><Num label="여유율(%)" value={waste} set={setWaste}/></Layout>}
export function FlooringQuantityCalculator(){const [a,setA]=useState(25),[box,setBox]=useState(2.2),[waste,setWaste]=useState(8);const n=Math.ceil(a*(1+waste/100)/Math.max(box,0.01));return <Layout result={<><span className="category-label">필요 바닥재</span><div className="result-main">약 {n}박스</div></>}><Num label="바닥 면적(㎡)" value={a} set={setA} step={0.1}/><Num label="1박스 시공면적(㎡)" value={box} set={setBox} step={0.01}/><Num label="여유율(%)" value={waste} set={setWaste}/></Layout>}
export function MovingBoxCalculator(){const [volume,setVolume]=useState(1200),[box,setBox]=useState(55),[waste,setWaste]=useState(15);const n=Math.ceil(volume*(1+waste/100)/Math.max(box,1));return <Layout result={<><span className="category-label">필요 박스</span><div className="result-main">약 {n}개</div></>}><Num label="짐 부피(L)" value={volume} set={setVolume}/><Num label="박스 1개 용량(L)" value={box} set={setBox}/><Num label="여유율(%)" value={waste} set={setWaste}/></Layout>}
export function MovingBudgetCalculator(){const [move,setMove]=useState(800000),[clean,setClean]=useState(250000),[install,setInstall]=useState(150000),[etc,setEtc]=useState(100000),[reserve,setReserve]=useState(10);const base=move+clean+install+etc,total=base*(1+reserve/100);return <Layout result={<><span className="category-label">이사 총예산</span><div className="result-main">{won(total)}</div><div className="stats"><div className="stat"><small>항목 합계</small><strong>{won(base)}</strong></div><div className="stat"><small>예비비</small><strong>{won(total-base)}</strong></div></div></>}><Num label="이사업체 비용" value={move} set={setMove}/><Num label="청소 비용" value={clean} set={setClean}/><Num label="설치·이전 비용" value={install} set={setInstall}/><Num label="기타 비용" value={etc} set={setEtc}/><Num label="예비비(%)" value={reserve} set={setReserve}/></Layout>}
export function SharedUtilityCalculator(){const [total,setTotal]=useState(240000),[people,setPeople]=useState(3),[my,setMy]=useState(1),[sum,setSum]=useState(3);const equal=total/Math.max(people,1),weighted=total*my/Math.max(sum,0.01);return <Layout result={<><span className="category-label">분담 결과</span><div className="result-main">균등 {won(equal)}</div><div className="stats"><div className="stat"><small>가중 분담</small><strong>{won(weighted)}</strong></div></div></>}><Num label="총 관리비·공과금" value={total} set={setTotal}/><Num label="인원수" value={people} set={setPeople}/><Num label="내 가중치" value={my} set={setMy} step={0.1}/><Num label="전체 가중치 합" value={sum} set={setSum} step={0.1}/></Layout>}
export function ElectricityEstimatorCalculator(){const [watts,setWatts]=useState(1200),[hours,setHours]=useState(4),[days,setDays]=useState(30),[rate,setRate]=useState(200);const kwh=watts/1000*hours*days,cost=kwh*rate;return <Layout result={<><span className="category-label">예상 사용비용</span><div className="result-main">약 {won(cost)}</div><div className="stats"><div className="stat"><small>예상 사용량</small><strong>{fmt(kwh,1)}kWh</strong></div></div></>}><Num label="소비전력(W)" value={watts} set={setWatts}/><Num label="하루 사용시간" value={hours} set={setHours} step={0.1}/><Num label="사용일수" value={days} set={setDays}/><Num label="평균 전력단가(원/kWh)" value={rate} set={setRate}/><div className="notice">실제 청구액은 누진구간, 기본요금, 세금 등에 따라 달라질 수 있습니다.</div></Layout>}
