"use client";
import { useState, type ReactNode } from "react";
const pad=(n:number)=>String(n).padStart(2,"0");
const fmt=(n:number,d=2)=>Number.isFinite(n)?n.toLocaleString("ko-KR",{maximumFractionDigits:d}):"0";
const won=(n:number)=>`${Math.round(Number.isFinite(n)?n:0).toLocaleString("ko-KR")}원`;
const Layout=({children,result}:{children:ReactNode,result:ReactNode})=><div className="tool-layout"><section className="panel">{children}</section><section className="panel">{result}<div className="action-row no-print"><button className="secondary" type="button" onClick={()=>window.print()}>인쇄 · PDF 저장</button></div></section></div>;
const Num=({label,value,set,min=0,step=1}:{label:string,value:number,set:(v:number)=>void,min?:number,step?:number})=><div className="field"><label>{label}</label><input type="number" min={min} step={step} value={value} onChange={e=>set(Number(e.target.value))}/></div>;
const Time=({label,value,set}:{label:string,value:string,set:(v:string)=>void})=><div className="field"><label>{label}</label><input type="time" value={value} onChange={e=>set(e.target.value)}/></div>;
const mins=(s:string)=>{const [h,m]=s.split(":").map(Number);return h*60+m};
const clock=(m:number)=>{const t=((m%1440)+1440)%1440;return `${pad(Math.floor(t/60))}:${pad(t%60)}`};

export function TimeDurationCalculator(){const [start,setStart]=useState("09:00"),[end,setEnd]=useState("18:30");const a=mins(start),b=mins(end),total=((b-a)+1440)%1440||1440;return <Layout result={<><span className="category-label">경과시간</span><div className="result-main">{Math.floor(total/60)}시간 {total%60}분</div><div className="stats"><div className="stat"><small>총 분</small><strong>{fmt(total,0)}분</strong></div><div className="stat"><small>시간 환산</small><strong>{fmt(total/60,2)}시간</strong></div></div></>}><Time label="시작 시각" value={start} set={setStart}/><Time label="종료 시각" value={end} set={setEnd}/><div className="notice">종료 시각이 더 이르면 다음 날 종료한 것으로 계산합니다.</div></Layout>}

export function DepartureTimeCalculator(){const [arrival,setArrival]=useState("09:00"),[travel,setTravel]=useState(60),[buffer,setBuffer]=useState(20);const leave=mins(arrival)-travel-buffer;return <Layout result={<><span className="category-label">권장 출발시각</span><div className="result-main">{clock(leave)}</div><div className="stats"><div className="stat"><small>이동시간</small><strong>{fmt(travel,0)}분</strong></div><div className="stat"><small>여유시간</small><strong>{fmt(buffer,0)}분</strong></div></div></>}><Time label="목표 도착시각" value={arrival} set={setArrival}/><Num label="예상 이동시간(분)" value={travel} set={setTravel}/><Num label="추가 여유시간(분)" value={buffer} set={setBuffer}/><div className="notice">교통체증·대기시간은 직접 여유시간에 반영하세요.</div></Layout>}

export function TripBudgetSplitCalculator(){const [shared,setShared]=useState(1200000),[people,setPeople]=useState(4),[personal,setPersonal]=useState(150000);const each=shared/Math.max(people,1),total=each+personal;return <Layout result={<><span className="category-label">1인당 예상 부담액</span><div className="result-main">{won(total)}</div><div className="stats"><div className="stat"><small>공동비용 분담</small><strong>{won(each)}</strong></div><div className="stat"><small>개인 추가비용</small><strong>{won(personal)}</strong></div></div></>}><Num label="공동 여행비 총액(원)" value={shared} set={setShared}/><Num label="분담 인원" value={people} set={setPeople} min={1}/><Num label="1인 개인 추가비용(원)" value={personal} set={setPersonal}/></Layout>}

export function LuggageWeightCalculator(){const [limit,setLimit]=useState(23),[current,setCurrent]=useState(18.4),[extra,setExtra]=useState(2);const final=current+extra,remain=limit-final;return <Layout result={<><span className="category-label">예상 최종 무게</span><div className="result-main">{fmt(final,1)}kg</div><div className="stats"><div className="stat"><small>{remain>=0?"남은 여유":"초과 중량"}</small><strong>{fmt(Math.abs(remain),1)}kg</strong></div><div className="stat"><small>허용중량</small><strong>{fmt(limit,1)}kg</strong></div></div><div className="notice">항공사·운임·노선별 실제 허용 기준을 반드시 별도로 확인하세요.</div></>}><Num label="허용중량(kg)" value={limit} set={setLimit} step={0.1}/><Num label="현재 짐 무게(kg)" value={current} set={setCurrent} step={0.1}/><Num label="추가 예정 무게(kg)" value={extra} set={setExtra} step={0.1}/></Layout>}

export function PaceCalculator(){const [distance,setDistance]=useState(5),[hours,setHours]=useState(0),[minutes,setMinutes]=useState(32),[seconds,setSeconds]=useState(30);const totalSec=Math.max(hours*3600+minutes*60+seconds,1),paceSec=totalSec/Math.max(distance,0.01),speed=distance/(totalSec/3600),pm=Math.floor(paceSec/60),ps=Math.round(paceSec%60);return <Layout result={<><span className="category-label">평균 페이스</span><div className="result-main">{pm}분 {pad(ps)}초/km</div><div className="stats"><div className="stat"><small>평균속도</small><strong>{fmt(speed,2)}km/h</strong></div><div className="stat"><small>총 시간</small><strong>{Math.floor(totalSec/60)}분 {totalSec%60}초</strong></div></div></>}><Num label="거리(km)" value={distance} set={setDistance} min={0.01} step={0.1}/><Num label="시간" value={hours} set={setHours}/><Num label="분" value={minutes} set={setMinutes}/><Num label="초" value={seconds} set={setSeconds}/><div className="notice">경사·휴식·신호대기 등은 반영하지 않은 평균 페이스입니다.</div></Layout>}
