"use client";
import ManualCalculatorLayout from "@/components/tools/ManualCalculatorLayout";
import { useMemo, useState, type ReactNode } from "react";

const dayMs=86400000;
const dateOnly=(s:string)=>{const [y,m,d]=s.split("-").map(Number);return y&&m&&d?new Date(y,m-1,d):new Date(NaN)};
const fmtDate=(d:Date)=>Number.isFinite(d.getTime())?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`:"날짜를 확인하세요";
const Layout=({children,result}:{children:ReactNode,result:ReactNode})=><ManualCalculatorLayout inputs={children} result={<section className="panel">{result}<div className="action-row no-print"><button className="secondary" type="button" onClick={()=>window.print()}>인쇄 · PDF 저장</button></div></section>}/>;
const DateField=({label,value,set,max}:{label:string,value:string,set:(v:string)=>void,max?:string})=><div className="field"><label>{label}</label><input type="date" required value={value} max={max} onChange={e=>{if(e.target.value)set(e.target.value)}}/></div>;
const Num=({label,value,set,step=1,min=0,max}:{label:string,value:number,set:(v:number)=>void,step?:number,min?:number,max?:number})=><div className="field"><label>{label}</label><input type="number" min={min} max={max} step={step} value={value} onChange={e=>{if(e.target.value!=="")set(Number(e.target.value))}}/></div>;

export function DatePeriodCalculator(){const [start,setStart]=useState("2026-08-23"),[end,setEnd]=useState("2026-12-31");const a=dateOnly(start),b=dateOnly(end),valid=Number.isFinite(a.getTime())&&Number.isFinite(b.getTime()),diff=valid?Math.round((b.getTime()-a.getTime())/dayMs):0,abs=Math.abs(diff);return <Layout result={<><span className="category-label">기간 결과</span><div className="result-main">{valid?(diff>=0?`${diff}일`:`${abs}일 전`):"날짜를 확인하세요"}</div><div className="stats"><div className="stat"><small>주 환산</small><strong>{(abs/7).toFixed(1)}주</strong></div><div className="stat"><small>개월 환산</small><strong>{(abs/30.44).toFixed(1)}개월</strong></div></div></>}><DateField label="시작일" value={start} set={setStart}/><DateField label="종료일" value={end} set={setEnd}/><div className="notice">개월 값은 평균 30.44일 기준 환산값입니다.</div></Layout>}

export function AgeCalculator(){const [birth,setBirth]=useState("1990-01-01"),[base,setBase]=useState("2026-08-23");const b=dateOnly(birth),t=dateOnly(base),valid=Number.isFinite(b.getTime())&&Number.isFinite(t.getTime())&&b.getTime()<=t.getTime();let age=0;let next=new Date(NaN);let days=0;if(valid){age=t.getFullYear()-b.getFullYear();const birthdayPassed=t.getMonth()>b.getMonth()||(t.getMonth()===b.getMonth()&&t.getDate()>=b.getDate());if(!birthdayPassed)age--;next=new Date(t.getFullYear(),b.getMonth(),b.getDate());if(next.getTime()<t.getTime())next=new Date(t.getFullYear()+1,b.getMonth(),b.getDate());days=Math.max(0,Math.ceil((next.getTime()-t.getTime())/dayMs));}return <Layout result={<><span className="category-label">만 나이</span><div className="result-main">{valid?`만 ${Math.max(age,0)}세`:"날짜를 확인하세요"}</div><div className="stats"><div className="stat"><small>다음 생일까지</small><strong>{valid?`${days}일`:"-"}</strong></div><div className="stat"><small>다음 생일</small><strong>{valid?fmtDate(next):"-"}</strong></div></div>{!valid?<div className="notice">생년월일은 기준일보다 미래일 수 없습니다.</div>:null}</>}><DateField label="생년월일" value={birth} set={setBirth} max={base}/><DateField label="기준일" value={base} set={setBase}/></Layout>}

export function SleepTimeCalculator(){const [sleep,setSleep]=useState(23),[wake,setWake]=useState(7);const safeSleep=Math.min(23,Math.max(0,sleep||0)),safeWake=Math.min(23,Math.max(0,wake||0)),duration=(safeWake-safeSleep+24)%24;return <Layout result={<><span className="category-label">수면 가능 시간</span><div className="result-main">{duration}시간</div><div className="notice">실제 잠드는 데 걸린 시간과 중간 각성 시간은 제외되지 않습니다.</div></>}><Num label="취침 시각(0~23시)" value={sleep} set={setSleep} min={0} max={23}/><Num label="기상 시각(0~23시)" value={wake} set={setWake} min={0} max={23}/></Layout>}

const commonItems=["신분증","지갑·결제수단","휴대전화","충전기","보조배터리","속옷·양말","세면도구","상비약"];
export function TravelPackingChecklist(){const [overseas,setOverseas]=useState(false),[days,setDays]=useState(3),[checked,setChecked]=useState<string[]>([]);const safeDays=Math.max(1,Math.round(days||1));const items=useMemo(()=>[...commonItems,...(overseas?["여권","항공권·예약확인서","해외결제 카드","변환 플러그"]:[]),...(safeDays>=4?["여벌 옷 추가","세탁용품"]:[])],[overseas,safeDays]);const toggle=(item:string)=>setChecked(v=>v.includes(item)?v.filter(x=>x!==item):[...v,item]);return <Layout result={<><span className="category-label">준비 진행률</span><div className="result-main">{checked.filter(x=>items.includes(x)).length}/{items.length}</div><div className="checklist">{items.map(item=><label key={item} style={{display:"block",marginTop:10}}><input type="checkbox" checked={checked.includes(item)} onChange={()=>toggle(item)}/> {item}</label>)}</div></>}><div className="field"><label>여행 유형</label><select value={overseas?"overseas":"domestic"} onChange={e=>setOverseas(e.target.value==="overseas")}><option value="domestic">국내여행</option><option value="overseas">해외여행</option></select></div><Num label="여행 기간(일)" value={days} set={setDays} min={1}/><div className="notice">목적지 날씨, 액티비티, 숙소 조건에 맞춰 필요한 항목을 추가로 확인하세요.</div></Layout>}

export function AnniversaryCycleCalculator(){const [start,setStart]=useState("2026-01-01"),[days,setDays]=useState(100);const d=dateOnly(start),valid=Number.isFinite(d.getTime());if(valid)d.setDate(d.getDate()+Math.max(Math.floor(days||0),0));return <Layout result={<><span className="category-label">계산된 날짜</span><div className="result-main">{valid?fmtDate(d):"날짜를 확인하세요"}</div><div className="notice">기준일 다음 날부터 날짜를 더하는 방식입니다.</div></>}><DateField label="기준일" value={start} set={setStart}/><Num label="추가할 일수" value={days} set={setDays}/></Layout>}
