"use client";
import { useMemo, useState, type ReactNode } from "react";

const dayMs=86400000;
const fmt=(n:number,d=2)=>Number.isFinite(n)?n.toLocaleString("ko-KR",{maximumFractionDigits:d}):"0";
const pad=(n:number)=>String(n).padStart(2,"0");
const dateOnly=(s:string)=>{const [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)};
const dateText=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const Layout=({children,result}:{children:ReactNode,result:ReactNode})=><div className="tool-layout"><section className="panel">{children}</section><section className="panel">{result}<div className="action-row no-print"><button className="secondary" type="button" onClick={()=>window.print()}>인쇄 · PDF 저장</button></div></section></div>;
const DateField=({label,value,set}:{label:string,value:string,set:(v:string)=>void})=><div className="field"><label>{label}</label><input type="date" value={value} onChange={e=>set(e.target.value)}/></div>;
const TimeField=({label,value,set}:{label:string,value:string,set:(v:string)=>void})=><div className="field"><label>{label}</label><input type="time" value={value} onChange={e=>set(e.target.value)}/></div>;
const Num=({label,value,set,min=0,step=1}:{label:string,value:number,set:(v:number)=>void,min?:number,step?:number})=><div className="field"><label>{label}</label><input type="number" value={value} min={min} step={step} onChange={e=>set(Number(e.target.value))}/></div>;

export function DateDurationCalculator(){const [start,setStart]=useState("2026-08-23"),[end,setEnd]=useState("2026-09-22");const a=dateOnly(start),b=dateOnly(end),valid=Number.isFinite(a.getTime())&&Number.isFinite(b.getTime())&&b.getTime()>=a.getTime(),days=valid?Math.round((b.getTime()-a.getTime())/dayMs):0,inclusive=valid?days+1:0,weeks=days/7;return <Layout result={<><span className="category-label">두 날짜 사이</span><div className="result-main">{fmt(days,0)}일</div><div className="stats"><div className="stat"><small>포함 일수</small><strong>{fmt(inclusive,0)}일</strong></div><div className="stat"><small>주 단위</small><strong>{fmt(weeks,2)}주</strong></div></div>{!valid?<div className="notice">종료일은 시작일과 같거나 이후 날짜여야 합니다.</div>:null}</>}><DateField label="시작일" value={start} set={setStart}/><DateField label="종료일" value={end} set={setEnd}/><div className="notice">경과 일수는 시작일을 제외한 날짜 차이이며, 포함 일수는 시작일과 종료일을 모두 셉니다.</div></Layout>}

export function AgeCalculator(){const [birth,setBirth]=useState("1990-10-10"),[base,setBase]=useState("2026-08-23");const b=dateOnly(birth),d=dateOnly(base),valid=Number.isFinite(b.getTime())&&Number.isFinite(d.getTime())&&d.getTime()>=b.getTime();let full=0,yearAge=0,nextBirthday="-",daysTo=0;if(valid){yearAge=d.getFullYear()-b.getFullYear();const hadBirthday=d.getMonth()>b.getMonth()||(d.getMonth()===b.getMonth()&&d.getDate()>=b.getDate());full=yearAge-(hadBirthday?0:1);let next=new Date(d.getFullYear(),b.getMonth(),b.getDate());if(next.getTime()<d.getTime())next=new Date(d.getFullYear()+1,b.getMonth(),b.getDate());nextBirthday=dateText(next);daysTo=Math.ceil((next.getTime()-d.getTime())/dayMs);}return <Layout result={<><span className="category-label">만 나이</span><div className="result-main">{valid?`${full}세`:"-"}</div><div className="stats"><div className="stat"><small>연 나이</small><strong>{valid?`${yearAge}세`:"-"}</strong></div><div className="stat"><small>다음 생일</small><strong>{valid?`${daysTo}일 후`:"-"}</strong></div></div>{valid?<div className="notice">다음 생일: {nextBirthday}</div>:<div className="notice">기준일은 생년월일 이후여야 합니다.</div>}</>}><DateField label="생년월일" value={birth} set={setBirth}/><DateField label="기준일" value={base} set={setBase}/></Layout>}

function toMinutes(s:string){const [h,m]=s.split(":").map(Number);return h*60+m;}
function clockText(total:number){const t=((total%1440)+1440)%1440;return `${pad(Math.floor(t/60))}:${pad(t%60)}`;}
export function SleepTimeCalculator(){const [bed,setBed]=useState("23:30"),[wake,setWake]=useState("07:00"),[target,setTarget]=useState(8);const a=toMinutes(bed),b=toMinutes(wake),minutes=((b-a)+1440)%1440||1440,hours=minutes/60,targetBed=clockText(b-target*60);return <Layout result={<><span className="category-label">수면 가능 시간</span><div className="result-main">{Math.floor(minutes/60)}시간 {minutes%60}분</div><div className="stats"><div className="stat"><small>시간 환산</small><strong>{fmt(hours,2)}시간</strong></div><div className="stat"><small>{fmt(target,1)}시간 확보 취침</small><strong>{targetBed}</strong></div></div><div className="notice">잠드는 데 걸리는 시간과 야간 각성은 반영하지 않은 일정 계획용 계산입니다.</div></>}><TimeField label="취침 시각" value={bed} set={setBed}/><TimeField label="기상 시각" value={wake} set={setWake}/><Num label="목표 수면시간" value={target} set={setTarget} min={1} step={0.5}/></Layout>}

const basicItems=["신분증","결제수단","휴대전화","충전기","예약정보","속옷·양말","여벌옷","세면도구","상비용품"];
const overseasItems=["여권","비자·입국서류 확인","해외 결제수단","변환 플러그","로밍·eSIM 확인","여행자보험 정보"];
const childItems=["아이 여벌옷","간식·물","물티슈","아이 상비용품","이동 중 놀거리"];
export function TravelChecklistCalculator(){const [overseas,setOverseas]=useState(true),[days,setDays]=useState(4),[child,setChild]=useState(false),[checked,setChecked]=useState<string[]>([]);const items=useMemo(()=>{const list=[...basicItems];if(days>=4)list.push("세탁·추가 의류 계획","보조배터리");if(overseas)list.push(...overseasItems);if(child)list.push(...childItems);return Array.from(new Set(list));},[overseas,days,child]);const done=items.filter(i=>checked.includes(i)).length;const toggle=(item:string)=>setChecked(prev=>prev.includes(item)?prev.filter(x=>x!==item):[...prev,item]);return <Layout result={<><span className="category-label">맞춤 준비물</span><div className="result-main">{done} / {items.length} 완료</div><div className="checklist">{items.map(item=><label key={item} className="check-row"><input type="checkbox" checked={checked.includes(item)} onChange={()=>toggle(item)}/><span>{item}</span></label>)}</div><div className="notice">여행지 날씨, 항공사 수하물, 숙소 제공품과 국가별 입국 규정을 추가 확인하세요.</div></>}><div className="field"><label>여행 유형</label><select value={overseas?"overseas":"domestic"} onChange={e=>setOverseas(e.target.value==="overseas")}><option value="domestic">국내여행</option><option value="overseas">해외여행</option></select></div><Num label="여행 기간(일)" value={days} set={setDays} min={1}/><div className="field"><label>아이 동반</label><select value={child?"yes":"no"} onChange={e=>setChild(e.target.value==="yes")}><option value="no">아니오</option><option value="yes">예</option></select></div><button className="secondary no-print" type="button" onClick={()=>setChecked([])}>체크 초기화</button></Layout>}

function addDays(base:string,days:number){const d=dateOnly(base);d.setDate(d.getDate()+days);return dateText(d);}
export function AnniversaryCycleCalculator(){const [base,setBase]=useState("2026-01-01"),[nth,setNth]=useState(365);const d=dateOnly(base),valid=Number.isFinite(d.getTime()),hundred=valid?addDays(base,99):"-",twoHundred=valid?addDays(base,199):"-",custom=valid?addDays(base,Math.max(Math.floor(nth),1)-1):"-";let anniversary="-";if(valid){const next=new Date(d.getFullYear()+1,d.getMonth(),d.getDate());anniversary=dateText(next);}return <Layout result={<><span className="category-label">주요 기념일</span><div className="result-main">{custom}</div><div className="stats"><div className="stat"><small>100일째</small><strong>{hundred}</strong></div><div className="stat"><small>200일째</small><strong>{twoHundred}</strong></div><div className="stat"><small>1주년</small><strong>{anniversary}</strong></div></div><div className="notice">기준일을 1일째로 계산합니다. 따라서 N일째는 기준일에서 N-1일을 더합니다.</div></>}><DateField label="기준일" value={base} set={setBase}/><Num label="확인할 N일째" value={nth} set={setNth} min={1}/></Layout>}
