"use client";

import { useMemo, useState } from "react";

type Field={key:string;label:string;defaultValue:number;unit?:string;step?:number;min?:number};
type Result={label:string;value:string};
const won=(n:number)=>`${Math.round(Number.isFinite(n)?n:0).toLocaleString("ko-KR")}원`;
const num=(n:number,d=1)=>`${(Number.isFinite(n)?n:0).toLocaleString("ko-KR",{maximumFractionDigits:d})}`;
const pct=(n:number)=>`${num(n,2)}%`;
const hour=(n:number)=>`${num(n,2)}시간`;
const ceil=(n:number)=>Math.ceil(Number.isFinite(n)?n:0);

const configs:Record<string,{fields:Field[];calc:(v:Record<string,number>)=>Result[]}>={
  "loan-payment-compare":{fields:[{key:"principal",label:"대출원금",defaultValue:100000000,unit:"원",step:1000000},{key:"rate",label:"연이율",defaultValue:4.5,unit:"%",step:.1},{key:"months",label:"상환기간",defaultValue:360,unit:"개월",step:12}],calc:v=>{const r=v.rate/1200,n=Math.max(1,v.months),p=v.principal;const equalPay=r===0?p/n:p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1);const equalPrincipalFirst=p/n+p*r;const equalPayTotal=equalPay*n;const equalPrincipalInterest=r===0?0:(p*r*(n+1))/2;return[{label:"원리금균등 월납입액",value:won(equalPay)},{label:"원리금균등 총이자",value:won(equalPayTotal-p)},{label:"원금균등 첫 달 납입액",value:won(equalPrincipalFirst)},{label:"원금균등 총이자",value:won(equalPrincipalInterest)}]}},
  "early-repayment-fee":{fields:[{key:"balance",label:"중도상환 원금",defaultValue:30000000,unit:"원",step:100000},{key:"feeRate",label:"수수료율",defaultValue:1.2,unit:"%",step:.1},{key:"remainingRatio",label:"잔존기간 비율",defaultValue:50,unit:"%",step:1}],calc:v=>[{label:"예상 중도상환수수료",value:won(v.balance*v.feeRate/100*v.remainingRatio/100)},{label:"수수료 포함 상환액",value:won(v.balance+v.balance*v.feeRate/100*v.remainingRatio/100)}]},
  "inflation-future-value":{fields:[{key:"today",label:"현재 금액",defaultValue:10000000,unit:"원",step:100000},{key:"inflation",label:"연 물가상승률",defaultValue:2.5,unit:"%",step:.1},{key:"years",label:"기간",defaultValue:10,unit:"년",step:1}],calc:v=>{const future=v.today*Math.pow(1+v.inflation/100,v.years);return[{label:"같은 구매력에 필요한 미래 금액",value:won(future)},{label:"증가분",value:won(future-v.today)},{label:"누적 물가상승",value:pct((future/v.today-1)*100)}]}},
  "break-even":{fields:[{key:"fixed",label:"고정비",defaultValue:5000000,unit:"원",step:100000},{key:"price",label:"단위 판매가",defaultValue:30000,unit:"원",step:1000},{key:"variable",label:"단위 변동비",defaultValue:12000,unit:"원",step:1000}],calc:v=>{const margin=Math.max(0,v.price-v.variable);const qty=margin>0?v.fixed/margin:0;return[{label:"단위 공헌이익",value:won(margin)},{label:"손익분기 판매량",value:`${ceil(qty).toLocaleString("ko-KR")}개`},{label:"손익분기 매출액",value:won(ceil(qty)*v.price)}]}},

  "wallpaper-cost":{fields:[{key:"area",label:"시공 면적",defaultValue:85,unit:"㎡",step:1},{key:"unit",label:"㎡당 자재·시공 단가",defaultValue:18000,unit:"원",step:1000},{key:"waste",label:"여유율",defaultValue:10,unit:"%",step:1}],calc:v=>{const bill=v.area*(1+v.waste/100);return[{label:"여유 포함 면적",value:`${num(bill)}㎡`},{label:"예상 도배비",value:won(bill*v.unit)}]}},
  "tile-installation-cost":{fields:[{key:"area",label:"타일 시공 면적",defaultValue:20,unit:"㎡",step:1},{key:"material",label:"㎡당 타일 자재비",defaultValue:25000,unit:"원",step:1000},{key:"labor",label:"㎡당 시공비",defaultValue:35000,unit:"원",step:1000},{key:"waste",label:"자재 여유율",defaultValue:8,unit:"%",step:1}],calc:v=>{const materialArea=v.area*(1+v.waste/100);return[{label:"타일 자재비",value:won(materialArea*v.material)},{label:"시공 인건비",value:won(v.area*v.labor)},{label:"예상 총비용",value:won(materialArea*v.material+v.area*v.labor)}]}},
  "heating-share":{fields:[{key:"total",label:"총 난방비",defaultValue:180000,unit:"원",step:10000},{key:"myArea",label:"내 사용면적",defaultValue:35,unit:"㎡",step:1},{key:"totalArea",label:"전체 사용면적",defaultValue:90,unit:"㎡",step:1}],calc:v=>{const ratio=v.totalArea>0?v.myArea/v.totalArea:0;return[{label:"내 면적 비율",value:pct(ratio*100)},{label:"면적 기준 분담액",value:won(v.total*ratio)}]}},

  "ice-vs-ev-cost":{fields:[{key:"km",label:"월 주행거리",defaultValue:1500,unit:"km",step:100},{key:"fuelEff",label:"내연기관 연비",defaultValue:12,unit:"km/L",step:.5},{key:"fuelPrice",label:"유가",defaultValue:1700,unit:"원/L",step:10},{key:"evEff",label:"전기차 전비",defaultValue:5.5,unit:"km/kWh",step:.1},{key:"elecPrice",label:"충전 단가",defaultValue:300,unit:"원/kWh",step:10}],calc:v=>{const ice=v.fuelEff>0?v.km/v.fuelEff*v.fuelPrice:0;const ev=v.evEff>0?v.km/v.evEff*v.elecPrice:0;return[{label:"내연기관 월 에너지비",value:won(ice)},{label:"전기차 월 충전비",value:won(ev)},{label:"월 차이",value:won(Math.abs(ice-ev))},{label:"연간 차이",value:won(Math.abs(ice-ev)*12)}]}},
  "annual-car-total":{fields:[{key:"fuel",label:"월 연료·충전비",defaultValue:180000,unit:"원",step:10000},{key:"insurance",label:"연 보험료",defaultValue:900000,unit:"원",step:50000},{key:"tax",label:"연 자동차세",defaultValue:400000,unit:"원",step:10000},{key:"parking",label:"월 주차·통행료",defaultValue:120000,unit:"원",step:10000},{key:"maintenance",label:"연 정비비",defaultValue:600000,unit:"원",step:50000}],calc:v=>{const annual=v.fuel*12+v.insurance+v.tax+v.parking*12+v.maintenance;return[{label:"연간 총 유지비",value:won(annual)},{label:"월평균 유지비",value:won(annual/12)}]}},
  "toll-fuel-trip":{fields:[{key:"distance",label:"왕복 주행거리",defaultValue:500,unit:"km",step:10},{key:"eff",label:"차량 연비",defaultValue:12,unit:"km/L",step:.5},{key:"fuel",label:"유가",defaultValue:1700,unit:"원/L",step:10},{key:"toll",label:"왕복 통행료",defaultValue:30000,unit:"원",step:1000},{key:"people",label:"분담 인원",defaultValue:4,unit:"명",step:1}],calc:v=>{const fuel=v.eff>0?v.distance/v.eff*v.fuel:0,total=fuel+v.toll;return[{label:"예상 유류비",value:won(fuel)},{label:"통행료 포함 총 교통비",value:won(total)},{label:"1인당 분담액",value:won(v.people>0?total/v.people:0)}]}},

  "n-plus-one-discount":{fields:[{key:"price",label:"상품 1개 가격",defaultValue:5000,unit:"원",step:100},{key:"buy",label:"유료 구매 개수",defaultValue:2,unit:"개",step:1},{key:"free",label:"무료 증정 개수",defaultValue:1,unit:"개",step:1}],calc:v=>{const totalQty=v.buy+v.free,total=v.price*v.buy;const normal=v.price*totalQty;return[{label:"총 수량",value:`${totalQty}개`},{label:"실제 결제액",value:won(total)},{label:"개당 실질가격",value:won(totalQty>0?total/totalQty:0)},{label:"실질 할인율",value:pct(normal>0?(1-total/normal)*100:0)}]}},
  "point-effective-price":{fields:[{key:"price",label:"결제금액",defaultValue:120000,unit:"원",step:1000},{key:"rate",label:"포인트 적립률",defaultValue:5,unit:"%",step:.5},{key:"pointValue",label:"포인트 1점 가치",defaultValue:1,unit:"원",step:.1}],calc:v=>{const points=v.price*v.rate/100;const benefit=points*v.pointValue;return[{label:"예상 적립 포인트",value:`${Math.round(points).toLocaleString("ko-KR")}P`},{label:"적립 가치",value:won(benefit)},{label:"실질 구매가",value:won(v.price-benefit)}]}},
  "landed-cost":{fields:[{key:"item",label:"상품가격",defaultValue:150000,unit:"원",step:1000},{key:"shipping",label:"해외 배송비",defaultValue:25000,unit:"원",step:1000},{key:"tax",label:"관부가세·세금 입력액",defaultValue:20000,unit:"원",step:1000},{key:"fee",label:"결제·대행 수수료",defaultValue:6000,unit:"원",step:1000}],calc:v=>{const total=v.item+v.shipping+v.tax+v.fee;return[{label:"부대비용 합계",value:won(v.shipping+v.tax+v.fee)},{label:"해외구매 총원가",value:won(total)},{label:"상품가 대비 추가비용",value:pct(v.item>0?(total/v.item-1)*100:0)}]}},

  "night-work-pay":{fields:[{key:"hourly",label:"기준 시급",defaultValue:12000,unit:"원",step:100},{key:"hours",label:"야간근로 시간",defaultValue:4,unit:"시간",step:.5},{key:"multiplier",label:"적용 배수",defaultValue:1.5,unit:"배",step:.1}],calc:v=>[{label:"야간근로 참고 수당",value:won(v.hourly*v.hours*v.multiplier)},{label:"기본 시급분",value:won(v.hourly*v.hours)},{label:"가산분",value:won(v.hourly*v.hours*Math.max(0,v.multiplier-1))}]},
  "holiday-work-pay":{fields:[{key:"hourly",label:"기준 시급",defaultValue:12000,unit:"원",step:100},{key:"hours",label:"휴일근로 시간",defaultValue:8,unit:"시간",step:.5},{key:"multiplier",label:"적용 배수",defaultValue:1.5,unit:"배",step:.1}],calc:v=>[{label:"휴일근로 참고 수당",value:won(v.hourly*v.hours*v.multiplier)},{label:"기본 시급분",value:won(v.hourly*v.hours)},{label:"가산분",value:won(v.hourly*v.hours*Math.max(0,v.multiplier-1))}]},
  "project-quote":{fields:[{key:"hours",label:"예상 작업시간",defaultValue:40,unit:"시간",step:1},{key:"rate",label:"목표 시간단가",defaultValue:50000,unit:"원",step:1000},{key:"expenses",label:"직접비·외주비",defaultValue:200000,unit:"원",step:10000},{key:"buffer",label:"리스크·수정 여유율",defaultValue:15,unit:"%",step:1}],calc:v=>{const base=v.hours*v.rate+v.expenses,total=base*(1+v.buffer/100);return[{label:"기본 견적원가",value:won(base)},{label:"여유비",value:won(total-base)},{label:"권장 견적액",value:won(total)}]}},

  "trip-expense-split":{fields:[{key:"lodging",label:"숙박비",defaultValue:400000,unit:"원",step:10000},{key:"transport",label:"교통비",defaultValue:180000,unit:"원",step:10000},{key:"food",label:"식비·공동경비",defaultValue:240000,unit:"원",step:10000},{key:"people",label:"인원",defaultValue:4,unit:"명",step:1}],calc:v=>{const total=v.lodging+v.transport+v.food;return[{label:"여행 공동경비",value:won(total)},{label:"1인당 균등 분담액",value:won(v.people>0?total/v.people:0)}]}},
  "group-dues":{fields:[{key:"target",label:"필요 총예산",defaultValue:1200000,unit:"원",step:10000},{key:"people",label:"회원 수",defaultValue:12,unit:"명",step:1},{key:"months",label:"모금 기간",defaultValue:6,unit:"개월",step:1},{key:"reserve",label:"예비비율",defaultValue:10,unit:"%",step:1}],calc:v=>{const total=v.target*(1+v.reserve/100);const monthly=v.people>0&&v.months>0?total/v.people/v.months:0;return[{label:"예비비 포함 목표액",value:won(total)},{label:"1인당 총 회비",value:won(v.people>0?total/v.people:0)},{label:"1인당 월 회비",value:won(monthly)}]}},
  "time-goal":{fields:[{key:"goal",label:"목표 누적시간",defaultValue:100,unit:"시간",step:1},{key:"done",label:"현재 누적시간",defaultValue:24,unit:"시간",step:1},{key:"daily",label:"하루 투자시간",defaultValue:1.5,unit:"시간",step:.5}],calc:v=>{const remain=Math.max(0,v.goal-v.done);const days=v.daily>0?remain/v.daily:0;return[{label:"남은 시간",value:hour(remain)},{label:"달성률",value:pct(v.goal>0?v.done/v.goal*100:0)},{label:"예상 남은 일수",value:`${ceil(days)}일`}]},
  "time-zone-difference":{fields:[{key:"from",label:"출발지 UTC 오프셋",defaultValue:9,unit:"시간",step:.5},{key:"to",label:"도착지 UTC 오프셋",defaultValue:-5,unit:"시간",step:.5},{key:"localHour",label:"출발지 시각(0~23.5)",defaultValue:9,unit:"시",step:.5}],calc:v=>{const diff=v.to-v.from;let h=(v.localHour+diff)%24;if(h<0)h+=24;const hh=Math.floor(h),mm=Math.round((h-hh)*60);return[{label:"시차",value:`${diff>=0?"+":""}${num(diff)}시간`},{label:"도착지 현지 시각",value:`${String(hh).padStart(2,"0")}:${String(mm).padStart(2,"0")}`}]}},
};

export default function NextWaveCalculator({type}:{type:string}){
  const config=configs[type];
  const initial=useMemo(()=>Object.fromEntries((config?.fields??[]).map(f=>[f.key,String(f.defaultValue)])),[config]);
  const [values,setValues]=useState<Record<string,string>>(initial);
  if(!config) return <div className="notice">계산기 설정을 찾을 수 없습니다.</div>;
  const parsed=Object.fromEntries(config.fields.map(f=>[f.key,Number(values[f.key]||0)]));
  const results=config.calc(parsed);
  return <div className="tool-layout">
    <div className="panel"><h2>값 입력</h2>{config.fields.map(f=><div className="field" key={f.key}><label htmlFor={`${type}-${f.key}`}>{f.label}</label><input id={`${type}-${f.key}`} type="number" value={values[f.key]??""} step={f.step??1} min={f.min??0} onChange={e=>setValues(s=>({...s,[f.key]:e.target.value}))}/>{f.unit?<div className="field-help">단위: {f.unit}</div>:null}</div>)}</div>
    <div className="panel"><h2>계산 결과</h2><div className="stats">{results.map((r,i)=><div className="stat" key={`${r.label}-${i}`}><small>{r.label}</small><strong>{r.value}</strong></div>)}</div><p className="resource-note">입력값을 바꾸면 결과가 즉시 갱신됩니다. 실제 계약·요금·법정 적용 기준이 있는 경우 최신 기준을 별도로 확인하세요.</p></div>
  </div>;
}
