"use client";
import { useState, type ReactNode } from "react";
const fmt=(n:number,d=2)=>Number.isFinite(n)?n.toLocaleString("ko-KR",{maximumFractionDigits:d}):"0";
const won=(n:number)=>`${Math.round(Number.isFinite(n)?n:0).toLocaleString("ko-KR")}원`;
const Layout=({children,result}:{children:ReactNode,result:ReactNode})=><div className="tool-layout"><section className="panel">{children}</section><section className="panel">{result}<div className="action-row no-print"><button className="secondary" type="button" onClick={()=>window.print()}>인쇄 · PDF 저장</button></div></section></div>;
const Num=({label,value,set,step=1}:{label:string,value:number,set:(n:number)=>void,step?:number})=><div className="field"><label>{label}</label><input type="number" min="0" step={step} value={value} onChange={e=>set(Number(e.target.value))}/></div>;
const DateField=({label,value,set}:{label:string,value:string,set:(v:string)=>void})=><div className="field"><label>{label}</label><input type="date" value={value} onChange={e=>set(e.target.value)}/></div>;
const dateOnly=(s:string)=>{const [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)};
const dayMs=86400000;
function weekdaysBetween(start:string,end:string){const a=dateOnly(start),b=dateOnly(end);if(!Number.isFinite(a.getTime())||!Number.isFinite(b.getTime())||b<a)return 0;let n=0;for(let d=new Date(a);d<=b;d=new Date(d.getTime()+dayMs)){const w=d.getDay();if(w!==0&&w!==6)n++;}return n;}
function addWeekdays(start:string,count:number){let d=dateOnly(start),left=Math.max(Math.floor(count),0);while(left>0){d=new Date(d.getTime()+dayMs);const w=d.getDay();if(w!==0&&w!==6)left--;}return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
export function WorkHoursCalculator(){const [start,setStart]=useState(9),[end,setEnd]=useState(18),[breakMin,setBreak]=useState(60);const gross=Math.max(end-start,0),net=Math.max(gross-breakMin/60,0);return <Layout result={<><span className="category-label">실근무시간</span><div className="result-main">{fmt(net,2)}시간</div><div className="stats"><div className="stat"><small>총 체류시간</small><strong>{fmt(gross,2)}시간</strong></div><div className="stat"><small>휴게시간</small><strong>{fmt(breakMin,0)}분</strong></div></div></>}><Num label="출근 시각(24시간, 예: 9)" value={start} set={setStart} step={0.5}/><Num label="퇴근 시각(24시간, 예: 18)" value={end} set={setEnd} step={0.5}/><Num label="휴게시간(분)" value={breakMin} set={setBreak}/><div className="notice">자정을 넘기는 근무, 대기시간 인정 여부 등은 별도로 확인하세요.</div></Layout>}
export function WeeklyHoursCalculator(){const [daily,setDaily]=useState(8),[days,setDays]=useState(5),[extra,setExtra]=useState(0);const regular=daily*days,total=regular+extra;return <Layout result={<><span className="category-label">주간 총 근로시간</span><div className="result-main">{fmt(total,1)}시간</div><div className="stats"><div className="stat"><small>기본 근로</small><strong>{fmt(regular,1)}시간</strong></div><div className="stat"><small>추가 근로</small><strong>{fmt(extra,1)}시간</strong></div></div></>}><Num label="하루 근로시간" value={daily} set={setDaily} step={0.5}/><Num label="주 근무일수" value={days} set={setDays}/><Num label="주 추가 근로시간" value={extra} set={setExtra} step={0.5}/></Layout>}
export function OvertimePayCalculator(){const [hourly,setHourly]=useState(11000),[hours,setHours]=useState(8),[mult,setMult]=useState(1.5);const pay=hourly*hours*mult;return <Layout result={<><span className="category-label">추가 수당 참고액</span><div className="result-main">{won(pay)}</div><div className="stats"><div className="stat"><small>기준 시급</small><strong>{won(hourly)}</strong></div><div className="stat"><small>적용 배수</small><strong>{fmt(mult,2)}배</strong></div></div><div className="notice">사업장 규모, 근로형태, 통상임금 범위, 야간·휴일 중복 등 실제 법정 산정조건을 확인하세요.</div></>}><Num label="기준 시급(원)" value={hourly} set={setHourly}/><Num label="연장·추가 근로시간" value={hours} set={setHours} step={0.5}/><Num label="적용 배수" value={mult} set={setMult} step={0.1}/></Layout>}
export function WeeklyHolidayPayCalculator(){const [hourly,setHourly]=useState(11000),[weekly,setWeekly]=useState(40);const paidHours=Math.min(Math.max(weekly,0)/40*8,8),pay=hourly*paidHours;return <Layout result={<><span className="category-label">주휴수당 단순 참고액</span><div className="result-main">{won(pay)}</div><div className="stats"><div className="stat"><small>환산 유급시간</small><strong>{fmt(paidHours,2)}시간</strong></div></div><div className="notice">주휴수당 발생 여부는 소정근로시간, 개근 여부, 근로계약 등 법정 요건을 따로 확인해야 합니다.</div></>}><Num label="시급(원)" value={hourly} set={setHourly}/><Num label="주 소정근로시간" value={weekly} set={setWeekly} step={0.5}/></Layout>}
export function AnnualLeaveBalanceCalculator(){const [granted,setGranted]=useState(15),[used,setUsed]=useState(6),[planned,setPlanned]=useState(2);const current=Math.max(granted-used,0),after=Math.max(granted-used-planned,0);return <Layout result={<><span className="category-label">계획 반영 후 잔여 연차</span><div className="result-main">{fmt(after,1)}일</div><div className="stats"><div className="stat"><small>현재 잔여</small><strong>{fmt(current,1)}일</strong></div><div className="stat"><small>사용 예정</small><strong>{fmt(planned,1)}일</strong></div></div></>}><Num label="회사에서 부여된 연차" value={granted} set={setGranted} step={0.5}/><Num label="이미 사용한 연차" value={used} set={setUsed} step={0.5}/><Num label="사용 예정 연차" value={planned} set={setPlanned} step={0.5}/><div className="notice">법정 발생일수를 자동 판정하지 않고 회사에서 확인한 부여일수를 기준으로 잔여량만 계산합니다.</div></Layout>}
export function TenureDurationCalculator(){const [start,setStart]=useState("2022-01-01"),[end,setEnd]=useState("2026-08-23");const a=dateOnly(start),b=dateOnly(end),days=b>=a?Math.floor((b.getTime()-a.getTime())/dayMs)+1:0,years=days/365.2425;return <Layout result={<><span className="category-label">근속기간</span><div className="result-main">{fmt(years,2)}년</div><div className="stats"><div className="stat"><small>달력 기준 일수</small><strong>{fmt(days,0)}일</strong></div></div><div className="notice">퇴직금·연차 등 법정 계속근로기간 산정에서는 휴직, 제외기간, 입퇴사일 처리 기준이 달라질 수 있습니다.</div></>}><DateField label="입사일" value={start} set={setStart}/><DateField label="기준일·퇴사일" value={end} set={setEnd}/></Layout>}
export function BusinessDaysCalculator(){const [start,setStart]=useState("2026-08-24"),[end,setEnd]=useState("2026-09-04");const days=weekdaysBetween(start,end);return <Layout result={<><span className="category-label">평일 영업일 수</span><div className="result-main">{fmt(days,0)}일</div><div className="notice">토·일만 제외합니다. 공휴일, 임시공휴일, 회사 휴무일은 자동 제외되지 않습니다.</div></>}><DateField label="시작일" value={start} set={setStart}/><DateField label="종료일" value={end} set={setEnd}/></Layout>}
export function DeadlineBusinessDayCalculator(){const [start,setStart]=useState("2026-08-24"),[days,setDays]=useState(10);const target=addWeekdays(start,days);return <Layout result={<><span className="category-label">예상 마감일</span><div className="result-main">{target}</div><div className="notice">시작일 다음 날부터 평일을 세며 토·일만 제외합니다. 법정 공휴일과 조직별 휴무일은 직접 조정하세요.</div></>}><DateField label="기준 시작일" value={start} set={setStart}/><Num label="추가할 영업일 수" value={days} set={setDays}/></Layout>}
export function FreelanceRateCalculator(){const [target,setTarget]=useState(4000000),[hours,setHours]=useState(100),[expense,setExpense]=useState(20);const base=target/Math.max(hours,1),rate=base*(1+expense/100);return <Layout result={<><span className="category-label">권장 시간당 청구단가</span><div className="result-main">{won(rate)}</div><div className="stats"><div className="stat"><small>목표소득 기준 시급</small><strong>{won(base)}</strong></div><div className="stat"><small>비용·비가동 보정</small><strong>{fmt(expense,1)}%</strong></div></div></>}><Num label="월 목표소득(원)" value={target} set={setTarget}/><Num label="월 청구 가능시간" value={hours} set={setHours}/><Num label="비용·비가동 보정률(%)" value={expense} set={setExpense}/><div className="notice">세금, 플랫폼 수수료, 장비비, 수정 횟수, 긴급 작업 프리미엄은 계약 조건에 맞게 추가 검토하세요.</div></Layout>}
export function MeetingCostCalculator(){const [people,setPeople]=useState(6),[hourly,setHourly]=useState(30000),[minutes,setMinutes]=useState(60);const cost=people*hourly*(minutes/60);return <Layout result={<><span className="category-label">예상 회의 인건비</span><div className="result-main">{won(cost)}</div><div className="stats"><div className="stat"><small>참석 인원</small><strong>{fmt(people,0)}명</strong></div><div className="stat"><small>회의시간</small><strong>{fmt(minutes,0)}분</strong></div></div></>}><Num label="참석 인원" value={people} set={setPeople}/><Num label="1인 평균 시간당 인건비(원)" value={hourly} set={setHourly}/><Num label="회의시간(분)" value={minutes} set={setMinutes}/></Layout>}
