"use client";
import {useState,type ReactNode} from "react";
const won=(n:number)=>`${Math.round(Number.isFinite(n)?n:0).toLocaleString("ko-KR")}원`;
const fmt=(n:number,d=2)=>Number.isFinite(n)?n.toLocaleString("ko-KR",{maximumFractionDigits:d}):"0";
const Layout=({children,result}:{children:ReactNode,result:ReactNode})=><div className="tool-layout"><section className="panel">{children}</section><section className="panel">{result}<div className="action-row no-print"><button className="secondary" type="button" onClick={()=>window.print()}>인쇄 · PDF 저장</button></div></section></div>;
const Num=({label,value,set,step=1}:{label:string,value:number,set:(n:number)=>void,step?:number})=><div className="field"><label>{label}</label><input type="number" min="0" step={step} value={value} onChange={e=>set(Number(e.target.value))}/></div>;

export function MinimumWageMonthlyCalculator(){const [hourly,setHourly]=useState(10320),[daily,setDaily]=useState(8),[weekly,setWeekly]=useState(40);const dailyPay=hourly*daily,weeklyPay=hourly*weekly,monthlySimple=hourly*weekly*52/12,official=hourly*209;return <Layout result={<><span className="category-label">2026 공식 월 환산액</span><div className="result-main">{won(official)}</div><div className="stats"><div className="stat"><small>일급</small><strong>{won(dailyPay)}</strong></div><div className="stat"><small>주급(근로시간만)</small><strong>{won(weeklyPay)}</strong></div><div className="stat"><small>단순 월 환산</small><strong>{won(monthlySimple)}</strong></div></div><div className="notice">시급 10,320원·월 209시간 공식 환산액은 주 40시간과 유급주휴 8시간을 포함한 기준입니다.</div></>}><Num label="시급(2026 기본값)" value={hourly} set={setHourly}/><Num label="하루 근로시간" value={daily} set={setDaily} step={0.5}/><Num label="주 근로시간" value={weekly} set={setWeekly} step={0.5}/></Layout>}

export function SalaryRaiseCalculator(){const [before,setBefore]=useState(3500000),[after,setAfter]=useState(3700000);const diff=after-before,rate=before>0?diff/before*100:0;return <Layout result={<><span className="category-label">급여 인상률</span><div className="result-main">{fmt(rate,2)}%</div><div className="stats"><div className="stat"><small>월·연 단위 증가액</small><strong>{won(diff)}</strong></div><div className="stat"><small>월급 기준 연간 증가액</small><strong>{won(diff*12)}</strong></div></div></>}><Num label="인상 전 급여" value={before} set={setBefore}/><Num label="인상 후 급여" value={after} set={setAfter}/><div className="notice">연봉을 입력하면 두 번째 ‘연간 증가액’ 표시는 참고하지 말고 인상률과 증가액만 확인하세요.</div></Layout>}

export function AnnualLeavePayCalculator(){const [daily,setDaily]=useState(120000),[days,setDays]=useState(5);const total=daily*days;return <Layout result={<><span className="category-label">예상 연차수당</span><div className="result-main">{won(total)}</div><div className="stats"><div className="stat"><small>1일 통상임금 입력값</small><strong>{won(daily)}</strong></div><div className="stat"><small>미사용 연차</small><strong>{fmt(days,1)}일</strong></div></div><div className="notice">지급 대상 여부와 1일 통상임금 산정은 자동 판정하지 않습니다.</div></>}><Num label="확인한 1일 통상임금" value={daily} set={setDaily}/><Num label="미사용 연차일수" value={days} set={setDays} step={0.5}/></Layout>}

export function WeeklyPayCalculator(){const [hourly,setHourly]=useState(10320),[dailyHours,setDailyHours]=useState(5),[days,setDays]=useState(5),[includeHoliday,setIncludeHoliday]=useState(true),[extraHours,setExtraHours]=useState(0),[extraMultiplier,setExtraMultiplier]=useState(1.5);const weeklyHours=dailyHours*days,base=hourly*weeklyHours,holidayHours=includeHoliday?Math.min(Math.max(weeklyHours,0)/40*8,8):0,holiday=hourly*holidayHours,extra=hourly*extraHours*extraMultiplier,total=base+holiday+extra;return <Layout result={<><span className="category-label">총 예상 주급</span><div className="result-main">{won(total)}</div><div className="stats"><div className="stat"><small>기본 주급</small><strong>{won(base)}</strong></div><div className="stat"><small>주휴수당 참고액</small><strong>{won(holiday)}</strong></div><div className="stat"><small>추가근무 수당</small><strong>{won(extra)}</strong></div><div className="stat"><small>주 소정근로시간</small><strong>{fmt(weeklyHours,1)}시간</strong></div></div><div className="notice">주휴수당과 가산수당의 실제 적용 여부는 자동 판정하지 않습니다. 근로계약과 최신 공식 기준을 확인하세요.</div></>}><Num label="시급(원)" value={hourly} set={setHourly}/><Num label="하루 근무시간" value={dailyHours} set={setDailyHours} step={0.5}/><Num label="주 근무일수" value={days} set={setDays} step={1}/><div className="field"><label>주휴수당 참고액 포함</label><select value={includeHoliday?"yes":"no"} onChange={e=>setIncludeHoliday(e.target.value==="yes")}><option value="yes">포함</option><option value="no">제외</option></select></div><Num label="추가근무시간" value={extraHours} set={setExtraHours} step={0.5}/><Num label="추가근무 적용 배수" value={extraMultiplier} set={setExtraMultiplier} step={0.1}/></Layout>}
